_BASE_: ../maskfiner_R50_bs16_160k.yaml
MODEL:
  META_ARCHITECTURE: "MaskFinerOracleTeacher"
  BACKBONE:
    NAME: "MixRes"
  MR:
    NAME: ["MixResViT","MixResNeighbour", "MixResNeighbour", "MixResNeighbour"]
    EMBED_DIM: [512,256,128,64]
    DEPTHS: [2, 2, 8, 12]
    NUM_HEADS: [ 32, 16, 8, 4 ]
    PATCH_SIZES: [32, 16, 8, 4]
    DROP_RATE: [0.0, 0.0, 0.0, 0.0]
    DROP_PATH_RATE: [0.0, 0.0, 0.0, 0.0]
    ATTN_DROP_RATE: [0.0, 0.0, 0.0, 0.0]
    UPSCALE_RATIO: [0.5, 0.5, 0.5, 0.5]
    SPLIT_RATIO: [4, 4, 4, 4]
    MLP_RATIO: [2., 2., 2., 2.]
    CLUSTER_SIZE: [8, 8, 8, 8]
    NBHD_SIZE: [48,48,48,48]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  WEIGHTS: "aff_mini.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MR_SEM_SEG_HEAD:
    NAME: "MaskPredictorOracleTeacher"
    CONVS_DIM: [512,256,128,128]
    TRANSFORMER_ENC_LAYERS: [1, 2, 4, 6]
  MASK_FINER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskFinerTransformerDecoderOracleTeacher"
    DEC_LAYERS: [3,3,4,9]
    DIM_FEEDFORWARD: [1024,1024,1024,1024]
    HIDDEN_DIM: [256,256,256,256]
    MASK_DIM: [256,256,256,256]
    NHEADS: [8, 8, 8, 8]
    ORACLE_TEACHER_RATIO: 0.8
    UPSAMPLING_WEIGHT: 10
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 80000
