_BASE_: ../maskfiner_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: ["MixResViT","MixResNeighbour", "MixResNeighbour", "MixResNeighbour"]
  MR:
    EMBED_DIM: [512,256,128,64]
    DEPTHS: [4, 4, 4, 4]
    NUM_HEADS: [ 32, 16, 8, 4 ]
    PATCH_SIZES: [32, 16, 8, 4]
    DROP_RATE: [0.0, 0.0, 0.0, 0.0]
    DROP_PATH_RATE: [0.3, 0.3, 0.3, 0.3]
    ATTN_DROP_RATE: [0.0, 0.0, 0.0, 0.0]
    SPLIT_RATIO: [4, 4, 4, 4]
    MLP_RATIO: [4., 4., 4., 4.]
    CLUSTER_SIZE: [8, 8, 8, 8]
    NBHD_SIZE: [48,48,48,48]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  WEIGHTS: "aff_mini.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 80000
