_BASE_: ../maskfiner_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "MixRes"
  MR:
    NAME: ["MixResViT"]
    EMBED_DIM: [512]
    DEPTHS: [2]
    NUM_HEADS: [ 32]
    PATCH_SIZES: [32]
    DROP_RATE: [0.0]
    DROP_PATH_RATE: [0.0]
    ATTN_DROP_RATE: [0.0]
    UPSCALE_RATIO: [0.0]
    SPLIT_RATIO: [4]
    MLP_RATIO: [2.]
    CLUSTER_SIZE: [8]
    NBHD_SIZE: [48]
    OUT_FEATURES: ["res2"]
  WEIGHTS: "aff_mini.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MR_SEM_SEG_HEAD:
    CONVS_DIM: [512]
    TRANSFORMER_ENC_LAYERS: [6]
    NHEADS: [16]
    IN_FEATURES: [ "res2" ]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ "res2" ]
    MLP_RATIO: [ 4.0 ]
  MASK_FINER:
    DEC_LAYERS: [10]
    DECODER_LEVELS: [1]
    DIM_FEEDFORWARD: [2048]
    HIDDEN_DIM: [256]
    MASK_DIM: [256]
    NHEADS: [8]
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 80000
