_BASE_: ../maskformer2_ml_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "MixResMetaLoss"
  MRML:
    EMBED_DIM: [256,256,256,256]
    DEPTHS: [10, 2, 2, 10]
    NUM_HEADS: [32, 32, 32, 32]
    PATCH_SIZES: [32, 16, 8, 4]
    DROP_RATE: 0.0
    DROP_PATH_RATE: 0.0
    SPLIT_RATIO: 4
    NUM_SCALES: 4
    UPSCALE_RATIO: 0.25
  WEIGHTS: "mrml_mini.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 80000
