# Copyright (c) Facebook, Inc. and its affiliates.

from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
from .maskfiner_transformer_decoder import MultiScaleMaskFinerTransformerDecoder
from .maskfiner_transformer_decoder_oracle_teacher import MultiScaleMaskFinerTransformerDecoderOracleTeacher
from .maskfiner_transformer_decoder_5s import MultiScaleMaskFinerTransformerDecoder5S
from .maskfiner_transformer_decoder_single_scale import SingleScaleMaskFinerTransformerDecoder
from .maskfiner_transformer_decoder_catfeatures import MultiScaleMaskFinerTransformerDecoderCat