_BASE_: ../maskformer2_ml_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "MixResMetaLossNeighbour"
  MRML:
    EMBED_DIM: [768,384,192,96]
    DEPTHS: [12, 4, 4, 12]
    NUM_HEADS: [24, 12, 6, 3]
    PATCH_SIZES: [32, 16, 8, 4]
    DROP_RATE: 0.0
    DROP_PATH_RATE: 0.3
    SPLIT_RATIO: 4
    MLP_RATIO: 3.0
    NUM_SCALES: 4
    UPSCALE_RATIO: 0.5
    CLUSTER_SIZE: 8
    NBHD_SIZE: [ 48, 48, 48, 48 ]
  WEIGHTS: "mrml_mini.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0002
  MAX_ITER: 80000
  WEIGHT_DECAY: 0.005
